---
# tasks file for jenkins_server

- name: Update
  become: yes
  apt:
    update_cache=yes

- name: Install system dependencies
  become: yes
  apt:
    name={{ item }}
    state=installed
  with_items: "{{ dependencies }}"

# Configure jenkins
- include: jenkins.yml

# Configure jenkins nodes
- include: nodes.yml

# Configure nginx
- include: nginx.yml

